import type { Metadata } from 'next';

import { barlow, barlow_condensed, bellefair } from '@/styles/fonts';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${barlow.variable} ${barlow_condensed.variable} ${bellefair.variable}`}
    >
      <body className="min-h-dvh antialiased">
        <main>{children}</main>
      </body>
    </html>
  );
}
